name: oasis-cleaning-quote-api
region: lon


services:
  - name: quote-api
    github:
      repo: welathfindrr13/-oasis-cleaning-website-
      branch: main
      deploy_on_push: true
    source_dir: /backend
    run_command: npm start
    build_command: npm install
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    health_check:
      http_path: /health
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "3000"
      - key: BREVO_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: QUOTES_FROM_EMAIL
        scope: RUN_AND_BUILD_TIME
        value: tyreeseedwards987@gmail.com
      - key: QUOTES_TO_EMAIL
        scope: RUN_AND_BUILD_TIME
        value: tyreeseedwards987@gmail.com
    routes:
      - path: /api

static_sites:
  - name: oasis-cleaning-frontend
    github:
      repo: welathfindrr13/-oasis-cleaning-website-
      branch: main
      deploy_on_push: true
    source_dir: /
    output_dir: /
    index_document: index.html
    routes:
      - path: /
