name: oasis-cleaning-quote-api
region: lon

# Static site component (frontend)
static_sites:
  - name: oasis-cleaning-frontend
    github:
      repo: welathfindrr13/-oasis-cleaning-website-
      branch: main
      deploy_on_push: true
    source_dir: /
    output_dir: /
    index_document: index.html
    error_document: 404.html
    catchall_document: index.html
    routes:
      - path: /
    envs:
      - key: QUOTE_API_ENDPOINT
        value: ${quote-api.PUBLIC_URL}/api/quote
        type: SECRET

# Backend API component
services:
  - name: quote-api
    github:
      repo: welathfindrr13/-oasis-cleaning-website-
      branch: main
      deploy_on_push: true
    source_dir: /backend
    run_command: npm start
    build_command: npm install
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    health_check:
      http_path: /health
      initial_delay_seconds: 20
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: BREVO_API_KEY
        type: SECRET
        # Set this in DigitalOcean dashboard with your Brevo API key
      - key: QUOTES_FROM_EMAIL
        value: tyreeseedwards@gmail.com
      - key: QUOTES_TO_EMAIL
        value: tyreeseedwards@gmail.com
      - key: ALLOWED_ORIGIN
        value: ${oasis-cleaning-frontend.PUBLIC_URL}
        type: SECRET
